### ISSUE TITLE
API checklist

### ISSUE THREAD

**Issue by TommyCpp** [TeamYouthChina/backend#207]
API Checklist for version 1.0

**Comment by JINHAOHU** [comment]
Article
- [ ] GET /articles/{id}

- [ ] PUT /articles/{id}

- [ ] POST /articles

- [ ] DELETE /articles/{id}

- [ ] POST /articles/{id}/comments

- [ ] PUT /articles/{id}/attention

- [ ] GET /articles/{id}/comments

**Comment by JINHAOHU** [comment]
- [ ] POST /questions

- [ ] GET /questions

- [ ] GET /questions/{id}

- [ ] DELETE /questions/{id}

- [ ] PUT /questions/{id}

- [ ] GET /questions/{id}/answers

- [ ] PUT /questions/{questionId}/invite/{userId}

- [ ] PUT /questions/{id}/invite

- [ ] PUT /questions/{id}/attention

**Comment by JINHAOHU** [comment]
Editorials

- [ ] GET /questions/{id}/attention

- [ ] DELETE /editorials/{id}

- [ ] PUT /editorials/{id}

- [ ] POST /editorials

- [ ] POST /editorials/{id}/comments

- [ ] GET /editorials/{id}/comments

- [ ] PUT /editorials/{id}/upvote

- [ ] PUT /editorials/{id}/attention

**Comment by JINHAOHU** [comment]
Job

- [ ] GET /jobs/{id}

- [ ] POST /jobs/search

**Comment by JINHAOHU** [comment]
Applicant

- [ ] GET /applicants/{id}

- [ ] PUT /applicants/{id}

- [ ] POST /applicants

- [ ] GET /applicants/{id}/contacts

- [ ] PUT /applicants/{id}/contacts

- [ ] POST /applicants/{id}/contacts

- [ ] GET /applicants/{id}/educations

- [ ] POST /applicants/{id}/educations

- [ ] PUT /applicants/{id}/educations

- [ ]  GET /applicants/{id}/projects

- [ ] POST /applicants/{id}/projects

- [ ] PUT /applicants/{id}/projects

- [ ] GET /applicants/{id}/experiences

- [ ]  POST /applicants/{id}/experiences

- [ ] PUT /applicants/{id}/experiences

- [ ] GET /applicants/{id}/certificates

- [ ] POST /applicants/{id}/certificates

- [ ] PUT /applicants/{id}/certificates

- [ ] GET /applicants/{id}/extracurriculars

- [ ] POST /applicants/{id}/extracurriculars

- [ ] PUT /applicants/{id}/extracurriculars

**Comment by JINHAOHU** [comment]
Answer

- [ ] POST /questions/{id}/answers

- [ ] GET /answers/{id}

- [ ] PUT /answers/{id}

- [ ] DELETE /answers/{id}

- [ ] POST /answers/{id}/comments

- [ ] GET /answers/{id}/comments

- [ ] PUT /answers/{id}/upvote

**Comment by JINHAOHU** [comment]
Application

- [ ] POST /jobs/{id}/apply

- [ ] GET /applicants/{id}/applications

**Comment by JINHAOHU** [comment]
GET applicants/{id} 的api works要改成experience, currentCompany改成String格式

**Comment by IrvingZhao2018** [comment]
> Job
> 
> * [x]  GET /jobs/{id}
> * [ ]  POST /jobs/search 

(JobSearch接口对上了, 部分功能未实现)

**Comment by JINHAOHU** [comment]
Security

- [ ]  POST /applicants/resgister

- [ ] GET /me

- [ ] POST /login

**Comment by IrvingZhao2018** [comment]
Company

- [ ] GET /companies/{id}

- [ ] PUT /companies/{id} 暂未开放

- [ ] POST /companies 暂未开放

- [ ] PUT /companies/{id}/attention

**Comment by JINHAOHU** [comment]
VIDEO

- [ ] GET /videos/{id}

- [ ] DELETE /videos/{id}

- [ ] POST /videos

- [ ] POST /videos/{id}/comments

- [ ] GET /videos/{id}/comments

- [ ] PUT /videos/{id}/upvote

- [ ] PUT /videos/{id}/attention

**Comment by JINHAOHU** [comment]
DISCOVER

- [ ] GET /job-for-you/intern

- [ ] GET /job-for-you/campus

- [ ] GET /job-for-you/general

- [ ] GET /home/new

- [ ] GET /home/hot

- [ ] GET /discovery/users

- [ ] GET /discovery/companies

- [ ] GET /discovery/articles

- [ ] GET /discovery/questions

- [ ] GET /discovery/jobs

**Comment by JINHAOHU** [comment]
Collection

- [ ] GET /users/{id}/attentions
// 拿收藏公司的时候返回的东西里面多了collect_id,  organization 应该改成company

- [ ] DELETE /jobs/attentions/{id}

- [ ] DELETE /companies/attentions/{id}

- [ ] DELETE /questions/attentions/{id}

- [ ] DELETE /articles/attentions/{id}

- [ ]

**Comment by jonathan12zhang** [comment]
DISCOVER

* [x]  GET /job-for-you/intern
* [x]  GET /job-for-you/campus
* [x]  GET /job-for-you/general
* [x]  GET /home/new
* [x]  GET /home/hot
* [x]  GET /discovery/users
  //把user的password删掉
* [x]  GET /discovery/companies
  // controller里的请求路径错了
* [x]  GET /discovery/articles
* [x]  GET /discovery/questions
* [x]  GET /discovery/jobs
  // controller里的请求路径错了

  //路径都更改好了

**Comment by Destiny123123** [comment]
QUESTION

* [x]  POST /questions
* [x]  GET /questions
  //返回的question没有转换成dto
* [x]  GET /questions/{id}
  // answer里面不应该有company_id
* [x]  DELETE /questions/{id}
* [x]  PUT /questions/{id}
* [x]  GET /questions/{id}/answers
  //返回的answer里面不应该有company_id
* [x]  PUT /questions/{questionId}/invite/{userId}
* [x]  PUT /questions/{id}/invite
* [x]  PUT /questions/{id}/attention

Answer

* [x]  POST /questions/{id}/answers
  // 返回的answer格式不对，少了很多东西，这个在question controller里面
//fix
